-- Active: 1725459882056@@127.0.0.1@5432@empresa_evaluacion_4
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
CREATE DATABASE empresa;
BEGIN;


CREATE TABLE IF NOT EXISTS public.empresa
(
    rut character(10) NOT NULL,
    nombre character(120) NOT NULL,
    direccion character(120) NOT NULL,
    telefono character(15) NOT NULL,
    correo character(80) NOT NULL,
    web character(50) NOT NULL,
    PRIMARY KEY (rut)
);

CREATE TABLE IF NOT EXISTS public.herramienta
(
    id_herramienta numeric(12) NOT NULL,
    nombre character(120) NOT NULL,
    precio_dia numeric(12) NOT NULL,
    PRIMARY KEY (id_herramienta)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    rut character(10) NOT NULL,
    nombre character(120) NOT NULL,
    correo character(80) NOT NULL,
    direccion character(120) NOT NULL,
    celular character(15) NOT NULL,
    PRIMARY KEY (rut)
);

CREATE TABLE IF NOT EXISTS public.arriendo
(
    folio numeric(12) NOT NULL,
    fecha date NOT NULL,
    dias numeric(5) NOT NULL,
    valor_dia numeric(12) NOT NULL,
    garantia character(30) NOT NULL,
    herramienta_id_herrramienta numeric(12) NOT NULL,
    cliente_rut character(10) NOT NULL,
    PRIMARY KEY (folio)
);

ALTER TABLE IF EXISTS public.arriendo
    ADD FOREIGN KEY (herramienta_id_herrramienta)
    REFERENCES public.herramienta (id_herramienta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.arriendo
    ADD FOREIGN KEY (cliente_rut)
    REFERENCES public.cliente (rut) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;


