-- Active: 1725459882056@@127.0.0.1@5432@sistemas_pagos
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.estudiantes
(
    id serial NOT NULL,
    nombre text NOT NULL,
    apellido text NOT NULL,
    fecha_nacimiento date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.curso
(
    id serial NOT NULL,
    nombre_curso text NOT NULL,
    costo FLOAT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pago
(
    id serial NOT NULL,
    monto FLOAT NOT NULL,
    fecha_pago date NOT NULL,
    metodo_pago text NOT NULL,
    estudiantes_id serial NOT NULL,
    curso_id serial NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.pago
    ADD FOREIGN KEY (curso_id)
    REFERENCES public.curso (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.pago
    ADD FOREIGN KEY (estudiantes_id)
    REFERENCES public.estudiantes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;