-- Active: 1725459882056@@127.0.0.1@5432@libreria_sesion5
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.editoriales
(
    codigo NUMERIC NOT NULL,
    nombre text NOT NULL,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public.libros
(
    codigo serial NOT NULL,
    titulo text NOT NULL,
    codigo_editorial serial NOT NULL,
    PRIMARY KEY (codigo)
);

ALTER TABLE IF EXISTS public.libros
    ADD FOREIGN KEY (codigo_editorial)
    REFERENCES public.editoriales (codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

-- Modificar la tabla “libros”, agregando la columna autor y precio.
ALTER TABLE libros ADD autor TEXT, ADD precio NUMERIC;

INSERT INTO editoriales(nombre)
VALUES('Anaya')

INSERT INTO editoriales(nombre)
VALUES('Andina')

INSERT INTO editoriales(nombre)
VALUES('S.M.')

-- Insertar editoriales y libros, de acuerdo con lo pedido
INSERT INTO libros(titulo,codigo_editorial,autor,precio)
VALUES('Don Quijote de la Mancha',1,'Miguel de Cervantes', 150 )


INSERT INTO libros(titulo,autor,precio)
VALUES('El Principito','Antoine SaintExupery', 120 )

INSERT INTO libros(titulo,autor,precio)
VALUES('El príncipe ','Maquiavelo', 180 )

INSERT INTO libros(titulo,codigo_editorial, autor,precio)
VALUES('Diplomacia',3,'Henry Kissinger', 180 )

INSERT INTO libros(titulo,codigo_editorial, autor,precio)
VALUES('Don Quijote de La Mancha II ',1,'Miguel de Cervantes ', 140 )

UPDATE libros
SET precio = 170
WHERE codigo = 4

-- Insertar 2 nuevos libros
INSERT INTO editoriales(nombre)
VALUES('Alma')

INSERT INTO editoriales(nombre)
VALUES('NOVA')

INSERT INTO libros(titulo,codigo_editorial,autor,precio) 
VALUES('Cumbres Borrascosas',4, 'Emily Bronte', 150)

INSERT INTO libros(titulo,codigo_editorial,autor,precio) 
VALUES('El imperio final',5, 'Brandon sanderson', 180)


-- Eliminar los libros de la editorial Anaya, solo en memoria (ROLLBACK)
BEGIN;
DELETE FROM libros
WHERE codigo_editorial = 1

ROLLBACK;
COMMIT;

-- Actualizar el nombre de la editorial Andina a Iberlibro en memoria, y actualizar el nombre de
-- la editorial S.M. a Mountain en disco duro (SAVEPOINT / ROLLBACK TO). 

BEGIN;

SAVEPOINT pp;

UPDATE editoriales
SET nombre = 'Iberlibro'
WHERE codigo = 2

ROLLBACK to pp;

UPDATE editoriales
SET nombre = 'Mountain'
WHERE codigo = 1

COMMIT;